{"timestamp":"2025-04-30T20:48:35.297699","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-04-30T20:48:35.298275","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/etl_covid.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-04-30T20:48:35.357734Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-04-30T20:48:35.358599Z","level":"info","event":" Previous state of the Task instance: queued","chan":"stdout","logger":"task"}
{"timestamp":"2025-04-30T20:48:35.359101Z","level":"info","event":"Current task name:criar_tabela","chan":"stdout","logger":"task"}
{"timestamp":"2025-04-30T20:48:35.359558Z","level":"info","event":"Dag name:etl_covid","chan":"stdout","logger":"task"}
{"timestamp":"2025-04-30T20:48:35.345439","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-04-30T20:48:35.367550","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowNotFoundException","exc_value":"The conn_id `meu_postgres` isn't defined","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/etl_covid.py","lineno":20,"name":"criar_tabela"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":725,"name":"run"},{"filename":"/usr/local/lib/python3.12/contextlib.py","lineno":137,"name":"__enter__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":832,"name":"_create_autocommit_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py","lineno":149,"name":"get_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":248,"name":"connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py","lineno":64,"name":"get_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py","lineno":482,"name":"get_connection_from_secrets"}]},{"exc_type":"AirflowRuntimeError","exc_value":"CONNECTION_NOT_FOUND: {'conn_id': 'meu_postgres'}","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py","lineno":472,"name":"get_connection_from_secrets"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py","lineno":142,"name":"get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/context.py","lineno":161,"name":"_get_connection"}]}]}
{"timestamp":"2025-04-30T20:48:35.386146Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-04-30T20:48:35.386843Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-04-30T20:48:35.388881Z","level":"info","event":"Task:<Task(PythonOperator): criar_tabela>","chan":"stdout","logger":"task"}
{"timestamp":"2025-04-30T20:48:35.389331Z","level":"info","event":"Failure caused by The conn_id `meu_postgres` isn't defined","chan":"stdout","logger":"task"}
